# Generated by Django 4.2.14 on 2025-01-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_rename_description_workout_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
    ]
