# Generated by Django 4.2.14 on 2025-01-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_lifetimereps_exercise_lifetime_reps_and_more'),
        ('workout', '0005_remove_workoutexercise_sets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutExercise',
            new_name='WorkoutSet',
        ),
    ]
