# Generated by Django 4.2.14 on 2025-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_rename_workoutexercise_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='elapsed_time',
            field=models.TimeField(default="00:00:00"),
            preserve_default=False,
        ),
    ]
