# Generated by Django 4.2.14 on 2025-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_workout_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='elapsed_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
