# Generated by Django 4.2.14 on 2025-01-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_workout_elapsed_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutset',
            name='unique_workout_exercise',
        ),
    ]
