# Generated by Django 5.2.1 on 2025-06-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_alter_workoutset_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='rest_time',
        ),
    ]
