# Generated by Django 5.2.1 on 2025-06-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_exerciserecord'),
        ('workout', '0012_rename_workoutset_workoutexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='exercise.exercise'),
        ),
    ]
