# Generated by Django 4.2.14 on 2025-01-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_exercise_favorited_by'),
        ('user', '0002_user_usergender_user_userheight_user_userweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_exercises',
            field=models.ManyToManyField(blank=True, to='exercise.exercise'),
        ),
    ]
