# Generated by Django 4.2.14 on 2025-01-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_favorite_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lifetimeWeightLifted',
            new_name='lifetime_weight_lifted',
        ),
    ]
