# Generated by Django 4.2.14 on 2025-01-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_lifetimeweightlifted_user_lifetime_weight_lifted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserGender',
            new_name='user_gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserHeight',
            new_name='user_height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserWeight',
            new_name='user_weight',
        ),
    ]
