# Generated by Django 5.2.1 on 2025-06-21 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_weightentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
