# Generated by Django 4.2.14 on 2025-01-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_exercise_favorited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='LifetimeReps',
            new_name='lifetime_reps',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='PersonalRecord',
            new_name='personal_record',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(related_name='exercises', to='exercise.tag'),
        ),
    ]
