# Generated by Django 4.2.14 on 2025-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_lifetimereps_exercise_lifetime_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='exercise.tag'),
        ),
    ]
