# Generated by Django 5.2.1 on 2025-06-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_exercise_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='lifetime_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='personal_record',
        ),
    ]
